/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Jul 26 10:48:43 2017. */

#include <datastruct.pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t msgDataSend_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, msgDataSend, text1, text1, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, msgDataSend, text2, text1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, msgDataSend, num1, text2, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, msgDataSend, num2, num1, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
