/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Mar 20 12:02:09 2017. */

#ifndef PB_FILE_PB_H_INCLUDED
#define PB_FILE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _File {
    char deviceID[16];
    uint32_t unixtime;
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    uint32_t offset;
    pb_callback_t data;
    bool finished;
    char contentType[32];
/* @@protoc_insertion_point(struct:File) */
} File;

typedef PB_BYTES_ARRAY_T(1024) File_data1KB_data_t;
typedef struct _File_data1KB {
    char deviceID[16];
    uint32_t unixtime;
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    uint32_t offset;
    File_data1KB_data_t data;
    bool finished;
    char contentType[32];
/* @@protoc_insertion_point(struct:File_data1KB) */
} File_data1KB;

typedef PB_BYTES_ARRAY_T(4096) File_data4KB_data_t;
typedef struct _File_data4KB {
    char deviceID[16];
    uint32_t unixtime;
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    uint32_t offset;
    File_data4KB_data_t data;
    bool finished;
    char contentType[32];
/* @@protoc_insertion_point(struct:File_data4KB) */
} File_data4KB;

/* Default values for struct fields */

/* Initializer values for message structs */
#define File_init_default                        {"", 0, false, 0, false, 0, 0, {{NULL}, NULL}, 0, ""}
#define File_data1KB_init_default                {"", 0, false, 0, false, 0, 0, {0, {0}}, 0, ""}
#define File_data4KB_init_default                {"", 0, false, 0, false, 0, 0, {0, {0}}, 0, ""}
#define File_init_zero                           {"", 0, false, 0, false, 0, 0, {{NULL}, NULL}, 0, ""}
#define File_data1KB_init_zero                   {"", 0, false, 0, false, 0, 0, {0, {0}}, 0, ""}
#define File_data4KB_init_zero                   {"", 0, false, 0, false, 0, 0, {0, {0}}, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define File_deviceID_tag                        1
#define File_unixtime_tag                        2
#define File_latitude_tag                        3
#define File_longitude_tag                       4
#define File_offset_tag                          5
#define File_data_tag                            6
#define File_finished_tag                        7
#define File_contentType_tag                     8
#define File_data1KB_deviceID_tag                1
#define File_data1KB_unixtime_tag                2
#define File_data1KB_latitude_tag                3
#define File_data1KB_longitude_tag               4
#define File_data1KB_offset_tag                  5
#define File_data1KB_data_tag                    6
#define File_data1KB_finished_tag                7
#define File_data1KB_contentType_tag             8
#define File_data4KB_deviceID_tag                1
#define File_data4KB_unixtime_tag                2
#define File_data4KB_latitude_tag                3
#define File_data4KB_longitude_tag               4
#define File_data4KB_offset_tag                  5
#define File_data4KB_data_tag                    6
#define File_data4KB_finished_tag                7
#define File_data4KB_contentType_tag             8

/* Struct field encoding specification for nanopb */
extern const pb_field_t File_fields[9];
extern const pb_field_t File_data1KB_fields[9];
extern const pb_field_t File_data4KB_fields[9];

/* Maximum encoded size of messages (where known) */
/* File_size depends on runtime parameters */
#define File_data1KB_size                        1103
#define File_data4KB_size                        4175

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FILE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
