/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Mon Dec 12 15:37:42 2016. */

#include "location.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Location_fields[18] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Location, deviceID, deviceID, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Location, unixtime, deviceID, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Location, latitude, unixtime, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, Location, longitude, latitude, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, Location, rfID, longitude, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, Location, onoff, rfID, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, Location, velocity, onoff, 0),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, Location, opendoor, velocity, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, Location, overVelocity, opendoor, 0),
    PB_FIELD( 10, BOOL    , OPTIONAL, STATIC  , OTHER, Location, overDriving, overVelocity, 0),
    PB_FIELD( 11, BOOL    , OPTIONAL, STATIC  , OTHER, Location, airCondition, overDriving, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, Location, fuel, airCondition, 0),
    PB_FIELD( 13, FLOAT   , OPTIONAL, STATIC  , OTHER, Location, temp, fuel, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, Location, carHeading, temp, 0),
    PB_FIELD( 15, UINT32  , OPTIONAL, STATIC  , OTHER, Location, pulseKm, carHeading, 0),
    PB_FIELD( 16, BOOL    , OPTIONAL, STATIC  , OTHER, Location, taxiGuest, pulseKm, 0),
    PB_FIELD( 17, BOOL    , OPTIONAL, STATIC  , OTHER, Location, taxiStop, taxiGuest, 0),
    PB_LAST_FIELD
};

const pb_field_t Locations_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Locations, data, data, &Location_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Locations, data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Location_Locations)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Locations, data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Location_Locations)
#endif


/* @@protoc_insertion_point(eof) */
