/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Dec 12 15:37:42 2016. */

#ifndef PB_LOCATION_PB_H_INCLUDED
#define PB_LOCATION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Locations {
    pb_callback_t data;
/* @@protoc_insertion_point(struct:Locations) */
} Locations;

typedef struct _Location {
    char deviceID[16];
    uint32_t unixtime;
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    bool has_rfID;
    char rfID[16];
    bool has_onoff;
    bool onoff;
    bool has_velocity;
    uint32_t velocity;
    bool has_opendoor;
    bool opendoor;
    bool has_overVelocity;
    bool overVelocity;
    bool has_overDriving;
    bool overDriving;
    bool has_airCondition;
    bool airCondition;
    bool has_fuel;
    float fuel;
    bool has_temp;
    float temp;
    bool has_carHeading;
    uint32_t carHeading;
    bool has_pulseKm;
    uint32_t pulseKm;
    bool has_taxiGuest;
    bool taxiGuest;
    bool has_taxiStop;
    bool taxiStop;
/* @@protoc_insertion_point(struct:Location) */
} Location;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Location_init_default                    {"", 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Locations_init_default                   {{{NULL}, NULL}}
#define Location_init_zero                       {"", 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Locations_init_zero                      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Locations_data_tag                       1
#define Location_deviceID_tag                    1
#define Location_unixtime_tag                    2
#define Location_latitude_tag                    3
#define Location_longitude_tag                   4
#define Location_rfID_tag                        5
#define Location_onoff_tag                       6
#define Location_velocity_tag                    7
#define Location_opendoor_tag                    8
#define Location_overVelocity_tag                9
#define Location_overDriving_tag                 10
#define Location_airCondition_tag                11
#define Location_fuel_tag                        12
#define Location_temp_tag                        13
#define Location_carHeading_tag                  14
#define Location_pulseKm_tag                     15
#define Location_taxiGuest_tag                   16
#define Location_taxiStop_tag                    17

/* Struct field encoding specification for nanopb */
extern const pb_field_t Location_fields[18];
extern const pb_field_t Locations_fields[2];

/* Maximum encoded size of messages (where known) */
#define Location_size                            96
/* Locations_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LOCATION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
