/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Feb 04 10:29:41 2017. */

#include "nats-streaming.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PubMsg_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, PubMsg, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, PubMsg, guid, clientID, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, PubMsg, subject, guid, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, PubMsg, reply, subject, 0),
    PB_FIELD(  5, BYTES   , REQUIRED, STATIC  , OTHER, PubMsg, data, reply, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, PubMsg, sha256, data, 0),
    PB_LAST_FIELD
};

const pb_field_t PubAck_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, PubAck, guid, guid, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, PubAck, error, guid, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgProto_fields[8] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, MsgProto, sequence, sequence, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MsgProto, subject, sequence, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, MsgProto, reply, subject, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, MsgProto, data, reply, 0),
    PB_FIELD(  5, INT64   , REQUIRED, STATIC  , OTHER, MsgProto, timestamp, data, 0),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, MsgProto, redelivered, timestamp, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, MsgProto, CRC32, redelivered, 0),
    PB_LAST_FIELD
};

const pb_field_t Ack_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Ack, subject, subject, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, Ack, sequence, subject, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectRequest_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ConnectRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ConnectRequest, heartbeatInbox, clientID, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectResponse_fields[8] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ConnectResponse, pubPrefix, pubPrefix, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, subRequests, pubPrefix, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, unsubRequests, subRequests, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, closeRequests, unsubRequests, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, error, closeRequests, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, subCloseRequests, error, 0),
    PB_FIELD(100, STRING  , REQUIRED, STATIC  , OTHER, ConnectResponse, publicKey, subCloseRequests, 0),
    PB_LAST_FIELD
};

const pb_field_t SubscriptionRequest_fields[11] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, SubscriptionRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, SubscriptionRequest, subject, clientID, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, SubscriptionRequest, qGroup, subject, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, SubscriptionRequest, inbox, qGroup, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, SubscriptionRequest, maxInFlight, inbox, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, SubscriptionRequest, ackWaitInSecs, maxInFlight, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, SubscriptionRequest, durableName, ackWaitInSecs, 0),
    PB_FIELD( 10, UENUM   , OPTIONAL, STATIC  , OTHER, SubscriptionRequest, startPosition, durableName, 0),
    PB_FIELD( 11, UINT64  , OPTIONAL, STATIC  , OTHER, SubscriptionRequest, startSequence, startPosition, 0),
    PB_FIELD( 12, INT64   , OPTIONAL, STATIC  , OTHER, SubscriptionRequest, startTimeDelta, startSequence, 0),
    PB_LAST_FIELD
};

const pb_field_t SubscriptionResponse_fields[3] = {
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , FIRST, SubscriptionResponse, ackInbox, ackInbox, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, SubscriptionResponse, error, ackInbox, 0),
    PB_LAST_FIELD
};

const pb_field_t UnsubscribeRequest_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, UnsubscribeRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, UnsubscribeRequest, subject, clientID, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, UnsubscribeRequest, inbox, subject, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, UnsubscribeRequest, durableName, inbox, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseRequest_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, CloseRequest, clientID, clientID, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseResponse_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, CloseResponse, error, error, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
